urdf: ../../../RobotSimulation/descriptions/autolife_robot/urdfs/robot_v0_52.urdf
link_radius: 0.05
base_links:
  - Link_Ground_Vehicle
  - Link_Ground_Vehicle
ee_links:
  - Link_Left_Gripper
  - Link_Right_Gripper
starting_config:
  [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ]
obstacles:
