urdf: ../../../RobotSimulation/descriptions/autolife_robot/urdfs/robot_v0_51.urdf
link_radius: 0.05
base_links:
  - link_Ground_Vehicle
  - link_Ground_Vehicle
ee_links:
  - link_Left_Wrist_Lower_to_Gripper
  - link_Right_Wrist_Lower_to_Gripper
starting_config:
  [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ]
obstacles:
